export enum TopicCategory {
  Politics = 'politics',
  Economy = 'economy',
  Entertainment = 'entertainment',
  Sports = 'sports',
  World = 'world',
  Lifestyle = 'lifestyle',
  Health = 'health',
  Science = 'science',
  Technology = 'technology',
  Culture = 'culture',
  History = 'history',
  Education = 'education',
  Society = 'society',
}