export enum CategoryNames {
  HOME = 'Home',
  REGISTER = 'Register',
  TRANSACTIONS = 'Transactions',
  ANALYSIS = 'Analysis',
  SETTINGS = 'Settings',
  MY_PROJECTS = 'My projects',
  DECLARATIONS = 'Declarations',
}

export enum MenuNames {
  HOME_EXCHANGE = 'HOME_EXCHANGE',
  HOME_SUPPLY = 'HOME_SUPPLY',
  HOME_REQUEST = 'HOME_REQUEST',
  HOME_SUPPLY_INFO = 'HOME_SUPPLY_INFO',
  HOME_REQUEST_INFO = 'HOME_REQUEST_INFO',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  PRIVACY = 'PRIVACY',
  COOKIE = 'COOKIE',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  VISITOR = 'VISITOR',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  FAVORITE_TOPICS = 'FAVORITE_TOPICS'  
}
